databricks_host="https://community.cloud.databricks.com/"
databricks_token=""
default_storage_account_key = "example"
custom_storage_account_key = "example"
secret_scope = "dev_secrets"
secret_key = "your-secret-key"